SET FOREIGN_KEY_CHECKS=0;
drop table Linea_comanda;
drop table Estat_Linia;
drop table comanda;
drop table Taula;
drop table Cambrer;
drop table Linea_Escandall;
drop table Ingredient;
drop table plat;
drop table categoria;
set FOREIGN_KEY_CHECKS=1;